services:
  emulator:
    image: redroid/redroid:15.0.0_64only-latest
    container_name: redroid-emulator
    privileged: true
    ports:
      - "5555:5555"
    volumes:
      - /home/anla/redroid-data:/data
    # Parameter untuk performa dan tampilan
    command:
      - androidboot.redroid_width=720
      - androidboot.redroid_height=1280
      - androidboot.redroid_fps=60
      - androidboot.redroid_gpu_mode=host
    stdin_open: true
    tty: true
